# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afce888db6e7df30884aa6aedefaa134bb5db520b12a34ea3b5fb281b4f92d04c9260a8cfae0fc57193fe6920b632cc8bc7c61209c08f7ff511e99a7e6d16cd2

test:
  secret_key_base: 4376e3289794fab0d9bf8c7b196909609ae374fd17360702bb89bfc15f382f0b891609e1954d30b04166d8e1d110591babe1a0828d74c0c84a0680ff9f4ece89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
